baseUrl: https://www.mertcan.vercel.app
files:
  - src/content/pages/about.mdx
  - src/content/pages/press.mdx
fileExtensions:
  - md
  - mdx
useGitIgnore: true
aliveStatusCodes:
  - 200
  - 201
  - 204
